# Generated by Django 6.0.7 on 2026-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100, verbose_name='Игра')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкая'), ('medium', 'Средняя'), ('hard', 'Сложная'), ('extreme', 'Экстремальная'), ('insane', 'Безумная')], max_length=20, verbose_name='Сложность')),
                ('players', models.CharField(choices=[('solo', '1 игрок'), ('duo', '2 игрока'), ('team', 'Команда')], max_length=20, verbose_name='Игроки')),
                ('challenge_type', models.CharField(choices=[('survival', 'Выживание'), ('exploration', 'Исследование'), ('building', 'Строительство'), ('boss', 'Босс'), ('speedrun', 'Скоростное прохождение'), ('random', 'Случайный')], max_length=20, verbose_name='Тип челленджа')),
                ('wishes', models.TextField(blank=True, verbose_name='Дополнительные пожелания')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('story', models.TextField(blank=True, verbose_name='История')),
                ('main_goal', models.TextField(blank=True, verbose_name='Главная цель')),
                ('rules', models.TextField(blank=True, verbose_name='Правила (каждое с новой строки)')),
                ('forbidden', models.TextField(blank=True, verbose_name='Запреты (каждый с новой строки)')),
                ('win_condition', models.TextField(blank=True, verbose_name='Условие победы')),
                ('difficulty_rating', models.CharField(blank=True, max_length=100, verbose_name='Оценка сложности')),
                ('estimated_time', models.CharField(blank=True, max_length=100, verbose_name='Примерное время прохождения')),
                ('generated_by_ai', models.BooleanField(default=False, verbose_name='Сгенерировано настоящим ИИ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Челлендж',
                'verbose_name_plural': 'Челленджи',
                'ordering': ['-created_at'],
            },
        ),
    ]
