# Generated by Django 6.0.7 on 2026-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Ключ сессии создателя'),
        ),
    ]
